<?php
	$books = array(
              array('name'          => 'Genesis',
                    'apiName'       => 'GEN',
                    'abbrevation'   => 'Gen.',
                    'chapterCount'  => 50,
                    'alternatives'  => ['geneses']
              ),
              array('name'          => 'Exodus',
                    'apiName'       => 'EXO',
                    'abbrevation'   => 'Ex.',
                    'chapterCount'  => 40,
                    'alternatives'  => ['exodes']
              ),
              array('name'          => 'Leviticus',
                    'apiName'       => 'LEV',
                    'abbrevation'   => 'Lev.',
                    'chapterCount'  => 27,
                    'alternatives'  => ['levitikus']
              ),
              array('name'          => 'Numeri',
                    'apiName'       => 'NUM',
                    'abbrevation'   => 'Num.',
                    'chapterCount'  => 36,
                    'alternatives'  => ['nummerie']
              ),
              array('name'          => 'Deuteronomium',
                    'apiName'       => 'DEU',
                    'abbrevation'   => 'Deut.',
                    'chapterCount'  => 34,
                    'alternatives'  => ['deu','deutronomium','deuteronomium']
              ),
              array('name'          => 'Jozua',
                    'apiName'       => 'JOS',
                    'abbrevation'   => 'Joz.',
                    'chapterCount'  => 24,
                    'alternatives'  => ['josua']
              ),
              array('name'          => 'Rechters',
                    'apiName'       => 'JDG',
                    'abbrevation'   => 'Recht.',
                    'chapterCount'  => 21,
                    'alternatives'  => ['rich','richteren','rigteren']
              ),
              array('name'          => 'Ruth',
                    'apiName'       => 'RUT',
                    'abbrevation'   => 'Ruth',
                    'chapterCount'  => 4,
                    'alternatives'  => ['ru','rut','rud']
              ),
              array('name'          => '1 Samuel',
                    'apiName'       => '1SA',
                    'abbrevation'   => '1 Sam.',
                    'chapterCount'  => 31,
                    'alternatives'  => ['samuel','sam']
              ),
              array('name'          => '2 Samuel',
                    'apiName'       => '2SA',
                    'abbrevation'   => '2 Sam.',
                    'chapterCount'  => 24,
                    'alternatives'  => ['samuel','sam']
              ),
              array('name'          => '1 Koningen',
                    'apiName'       => '1KI',
                    'abbrevation'   => '1 Kon.',
                    'chapterCount'  => 22,
                    'alternatives'  => ['koningen']
              ),
              array('name'          => '2 Koningen',
                    'apiName'       => '2KI',
                    'abbrevation'   => '2 Kon.',
                    'chapterCount'  => 25,
                    'alternatives'  => ['koningen']
              ),
              array('name'          => '1 Kronieken',
                    'apiName'       => '1CH',
                    'abbrevation'   => '1 Kron.',
                    'chapterCount'  => 29,
                    'alternatives'  => ['1kro']
              ),
              array('name'          => '2 Kronieken',
                    'apiName'       => '2CH',
                    'abbrevation'   => '2 Kron.',
                    'chapterCount'  => 36,
                    'alternatives'  => ['2kro']
              ),
              array('name'          => 'Ezra',
                    'apiName'       => 'EZR',
                    'abbrevation'   => 'Ezra',
                    'chapterCount'  => 10,
                    'alternatives'  => ['esra','esr','ezr']
              ),
              array('name'          => 'Nehemia',
                    'apiName'       => 'NEH',
                    'abbrevation'   => 'Neh.',
                    'chapterCount'  => 13,
                    'alternatives'  => ['neheemia']
              ),
              array('name'          => 'Ester',
                    'apiName'       => 'EST',
                    'abbrevation'   => 'Est.',
                    'chapterCount'  => 10,
                    'alternatives'  => ['esther']
              ),
              array('name'          => 'Job',
                    'apiName'       => 'JOB',
                    'abbrevation'   => 'Job',
                    'chapterCount'  => 42,
                    'alternatives'  => ['jop']
              ),
              array('name'          => 'Psalmen',
                    'apiName'       => 'PSA',
                    'abbrevation'   => 'Ps.',
                    'chapterCount'  => 150,
                    'alternatives'  => ['psa','psalm','spalm']
              ),
              array('name'          => 'Spreuken',
                    'apiName'       => 'PRO',
                    'abbrevation'   => 'Spr.',
                    'chapterCount'  => 31,
                    'alternatives'  => ['sp']
              ),
              array('name'          => 'Prediker',
                    'apiName'       => 'ECC',
                    'abbrevation'   => 'Pred.',
                    'chapterCount'  => 12,
                    'alternatives'  => ['pre','pr']
              ),
              array('name'          => 'Hooglied',
                    'apiName'       => 'SNG',
                    'abbrevation'   => 'Hoogl.',
                    'chapterCount'  => 8,
                    'alternatives'  => ['hoog','hoo']
              ),
              array('name'          => 'Jesaja',
                    'apiName'       => 'ISA',
                    'abbrevation'   => 'Jes.',
                    'chapterCount'  => 66,
                    'alternatives'  => ['jesajah']
              ),
              array('name'          => 'Jeremia',
                    'apiName'       => 'JER',
                    'abbrevation'   => 'Jer.',
                    'chapterCount'  => 52,
                    'alternatives'  => ['jr']
              ),
              array('name'          => 'Klaagliederen',
                    'apiName'       => 'LAM',
                    'abbrevation'   => 'Klaagl.',
                    'chapterCount'  => 5,
                    'alternatives'  => ['kla','kl']
              ),
              array('name'          => 'Ezechiël',
                    'apiName'       => 'EZK',
                    'abbrevation'   => 'Ezech.',
                    'chapterCount'  => 48,
                    'alternatives'  => ['eze','ezegiel','esegiel']
              ),
              array('name'          => 'Daniël',
                    'apiName'       => 'DAN',
                    'abbrevation'   => 'Dan.',
                    'chapterCount'  => 12,
                    'alternatives'  => ['da']
              ),
              array('name'          => 'Hosea',
                    'apiName'       => 'HOS',
                    'abbrevation'   => 'Hos.',
                    'chapterCount'  => 14,
                    'alternatives'  => ['hoz','hozea']
              ),
              array('name'          => 'Joël',
                    'apiName'       => 'JOL',
                    'abbrevation'   => 'Joël',
                    'chapterCount'  => 4,
                    'alternatives'  => ['jl']
              ),
              array('name'          => 'Amos',
                    'apiName'       => 'AMO',
                    'abbrevation'   => 'Amos',
                    'chapterCount'  => 9,
                    'alternatives'  => ['am','amoz']
              ),
              array('name'          => 'Obadja',
                    'apiName'       => 'OBA',
                    'abbrevation'   => 'Ob.',
                    'chapterCount'  => 1,
                    'alternatives'  => ['oba']
              ),
              array('name'          => 'Jona',
                    'apiName'       => 'JON',
                    'abbrevation'   => 'Jona',
                    'chapterCount'  => 4,
                    'alternatives'  => ['jon']
              ),
              array('name'          => 'Micha',
                    'apiName'       => 'MIC',
                    'abbrevation'   => 'Micha',
                    'chapterCount'  => 7,
                    'alternatives'  => ['mic','miga']
              ),
              array('name'          => 'Nahum',
                    'apiName'       => 'NAM',
                    'abbrevation'   => 'Nah.',
                    'chapterCount'  => 3,
                    'alternatives'  => ['na']
              ),
              array('name'          => 'Habakuk',
                    'apiName'       => 'HAB',
                    'abbrevation'   => 'Hab.',
                    'chapterCount'  => 3,
                    'alternatives'  => ['habbakuk']
              ),
              array('name'          => 'Sefanja',
                    'apiName'       => 'ZEP',
                    'abbrevation'   => 'Sef.',
                    'chapterCount'  => 3,
                    'alternatives'  => ['zef','zefanja']
              ),
              array('name'          => 'Haggai',
                    'apiName'       => 'HAG',
                    'abbrevation'   => 'Hag.',
                    'chapterCount'  => 2,
                    'alternatives'  => []
              ),
              array('name'          => 'Zacharia',
                    'apiName'       => 'ZEC',
                    'abbrevation'   => 'Zach.',
                    'chapterCount'  => 14,
                    'alternatives'  => ['za','zagaria','zaggaria','zagarja','sacharia']
              ),
              array('name'          => 'Maleachi',
                    'apiName'       => 'MAL',
                    'abbrevation'   => 'Mal.',
                    'chapterCount'  => 3,
                    'alternatives'  => ['malagie','malliagie','malliachie','malleachie','maleachie']
              ),
              array('name'          => 'Matteüs',
                    'apiName'       => 'MAT',
                    'abbrevation'   => 'Mat.',
                    'chapterCount'  => 28,
                    'alternatives'  => ['mateus','matteus','matt']
              ),
              array('name'          => 'Marcus',
                    'apiName'       => 'MRK',
                    'abbrevation'   => 'Marc.',
                    'chapterCount'  => 16,
                    'alternatives'  => ['mar','markus','mark']
              ),
              array('name'          => 'Lucas',
                    'apiName'       => 'LUK',
                    'abbrevation'   => 'Luc.',
                    'chapterCount'  => 24,
                    'alternatives'  => ['lukas','luk','lu']
              ),
              array('name'          => 'Johannes',
                    'apiName'       => 'JHN',
                    'abbrevation'   => 'Joh.',
                    'chapterCount'  => 21,
                    'alternatives'  => ['johanes']
              ),
              array('name'          => 'Handelingen',
                    'apiName'       => 'ACT',
                    'abbrevation'   => 'Hand.',
                    'chapterCount'  => 28,
                    'alternatives'  => ['hd']
              ),
              array('name'          => 'Romeinen',
                    'apiName'       => 'ROM',
                    'abbrevation'   => 'Rom.',
                    'chapterCount'  => 16,
                    'alternatives'  => ['romijnen','ro','rm']
              ),
              array('name'          => '1 Korintiërs',
                    'apiName'       => '1CO',
                    'abbrevation'   => '1 Kor.',
                    'chapterCount'  => 16,
                    'alternatives'  => ['1corienthiers','1cor','1korinthe','korinthiers','korinthe']
              ),
              array('name'          => '2 Korintiërs',
                    'apiName'       => '2CO',
                    'abbrevation'   => '2 Kor.',
                    'chapterCount'  => 13,
                    'alternatives'  => ['2corienthiers','2cor','2korinthe','korinthiers','korinthe']
              ),
              array('name'          => 'Galaten',
                    'apiName'       => 'GAL',
                    'abbrevation'   => 'Gal.',
                    'chapterCount'  => 6,
                    'alternatives'  => ['ga','gl']
              ),
              array('name'          => 'Efeziërs',
                    'apiName'       => 'EPH',
                    'abbrevation'   => 'Ef.',
                    'chapterCount'  => 6,
                    'alternatives'  => ['efe','efesiers','efeze']
              ),
              array('name'          => 'Filippenzen',
                    'apiName'       => 'PHP',
                    'abbrevation'   => 'Filip.',
                    'chapterCount'  => 4,
                    'alternatives'  => ['filiepenzen','filiepensen','fillip','fi','fil','fl']
              ),
              array('name'          => 'Kolossenzen',
                    'apiName'       => 'COL',
                    'abbrevation'   => 'Kol.',
                    'chapterCount'  => 4,
                    'alternatives'  => ['col']
              ),
              array('name'          => '1 Tessalonicenzen',
                    'apiName'       => '1TH',
                    'abbrevation'   => '1 Tes.',
                    'chapterCount'  => 5,
                    'alternatives'  => ['1tess','1tessalonisensen','tessalonicenzen','tessalonisensen']
              ),
              array('name'          => '2 Tessalonicenzen',
                    'apiName'       => '2TH',
                    'abbrevation'   => '2 Tes.',
                    'chapterCount'  => 3,
                    'alternatives'  => ['2tess','2tessalonisensen','tessalonicenzen','tessalonisensen']
              ),
              array('name'          => '1 Timoteüs',
                    'apiName'       => '1TI',
                    'abbrevation'   => '1 Tim.',
                    'chapterCount'  => 6,
                    'alternatives'  => ['1timo','1timotheus','timo','timoteus','timotheus']
              ),
              array('name'          => '2 Timoteüs',
                    'apiName'       => '2TI',
                    'abbrevation'   => '2 Tim.',
                    'chapterCount'  => 4,
                    'alternatives'  => ['2timo','2timotheus','timo','timoteus','timotheus']
              ),
              array('name'          => 'Titus',
                    'apiName'       => 'TIT',
                    'abbrevation'   => 'Tit.',
                    'chapterCount'  => 3,
                    'alternatives'  => ['tites']
              ),
              array('name'          => 'Filemon',
                    'apiName'       => 'PHM',
                    'abbrevation'   => 'Filem.',
                    'chapterCount'  => 1,
                    'alternatives'  => ['file','fi','fil','fl']
              ),
              array('name'          => 'Hebreeën',
                    'apiName'       => 'HEB',
                    'abbrevation'   => 'Hebr.',
                    'chapterCount'  => 13,
                    'alternatives'  => ['heb','hbr','hb','heebreeen','hebreen']
              ),
              array('name'          => 'Jakobus',
                    'apiName'       => 'JAS',
                    'abbrevation'   => 'Jak.',
                    'chapterCount'  => 5,
                    'alternatives'  => ['jac','jakobes','jacobes']
              ),
              array('name'          => '1 Petrus',
                    'apiName'       => '1PE',
                    'abbrevation'   => '1 Petr.',
                    'chapterCount'  => 5,
                    'alternatives'  => ['1pet','petrus']
              ),
              array('name'          => '2 Petrus',
                    'apiName'       => '2PE',
                    'abbrevation'   => '2 Petr.',
                    'chapterCount'  => 3,
                    'alternatives'  => ['2pet','petrus']
              ),
              array('name'          => '1 Johannes',
                    'apiName'       => '1JN',
                    'abbrevation'   => '1 Joh.',
                    'chapterCount'  => 5,
                    'alternatives'  => ['1joh']
              ),
              array('name'          => '2 Johannes',
                    'apiName'       => '2JN',
                    'abbrevation'   => '2 Joh.',
                    'chapterCount'  => 1,
                    'alternatives'  => ['2joh']
              ),
              array('name'          => '3 Johannes',
                    'apiName'       => '3JN',
                    'abbrevation'   => '3 Joh.',
                    'chapterCount'  => 1,
                    'alternatives'  => ['3joh']
              ),
              array('name'          => 'Judas',
                    'apiName'       => 'JUD',
                    'abbrevation'   => 'Judas',
                    'chapterCount'  => 1,
                    'alternatives'  => ['jud']
              ),
              array('name'          => 'Openbaring',
                    'apiName'       => 'REV',
                    'abbrevation'   => 'Op.',
                    'chapterCount'  => 22,
                    'alternatives'  => ['open']
              ));

echo json_encode($books);

?>
